_BASE_: "Base.yaml"
SOLVER:
  TYPE: "sgd"
  IMS_PER_BATCH: 8
  BASE_LR: 0.1
  STEPS: (100, 1000)
  MAX_ITER: 10000 #4972
  WARMUP_ITERS: 0
TEST:
  EVAL_PERIOD: 1000
VIS_PERIOD: 1 
DATASETS:
  TRAIN: ('SUNRGBD_train_mini', 'SUNRGBD_val_mini')
  TEST: ('SUNRGBD_test_mini',) 
  CATEGORY_NAMES: ('chair', 'table', 'cabinet', 'car', 'lamp', 'books', 'sofa', 'pedestrian', 'picture', 'window', 'pillow', 'truck', 'door', 'blinds', 'sink', 'shelves', 'television', 'shoes', 'cup', 'bottle', 'bookcase', 'laptop', 'desk', 'cereal box', 'floor mat', 'traffic cone', 'mirror', 'barrier', 'counter', 'camera', 'bicycle', 'toilet', 'bus', 'bed', 'refrigerator', 'trailer', 'box', 'oven', 'clothes', 'van', 'towel', 'motorcycle', 'night stand', 'stove', 'machine', 'stationery', 'bathtub', 'cyclist', 'curtain', 'bin')
MODEL:
  ROI_HEADS:
    NAME: 'ROIHeads_Score' # name of the class that is the 3d predictor
    NUM_CLASSES: 50
  ROI_CUBE_HEAD:
    NAME: 'CubeHead_vanilla' # name of the 3d head
    DIMS_PRIORS_ENABLED: False
    POOLER_TYPE: 'ROIAlignV2'
    POOLER_RESOLUTION: 1
  META_ARCHITECTURE: 'ScoreNet' # name of the overall arch that calls the ROI_HEADS.NAME and ROI_CUBE_HEAD.NAME